Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:
a) Диагональная, ортогональная, но не единичная(!)


In [1]:
import numpy as np
from math import *

In [2]:
a = pi #любой угол
A = np.array([
    [cos(a), 0, 0],
    [0, cos(a), 0],
    [0, 0, cos(a)]
])

np.dot(A, A.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

b) Верхнетреугольная, ортогональная

In [17]:
B = np.eye(3, M=None, k=0,  order='C')
np.dot(B, B.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

c) Нижнетреугольная, ортогональная

In [ ]:
C = np.eye(3, M=None, k=0,  order='C')
np.dot(C, C.T)

d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [21]:
# a некий угол, какой неважно из основного тригонометрического тождества
D = np.array([
    [cos(a), sin(a)],
    [-sin(a), cos(a)]
])

np.linalg.det(D)

0.9999999999999999

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [30]:
m = np.array([[2, 2], [1, 3]]) 
print(m)

wm, vm = np.linalg.eig(m)

for items in range(len(wm)):
    print(wm[items])
    print(vm[:,items])


[[2 2]
 [1 3]]
1.0
[-0.89442719  0.4472136 ]
4.0
[-0.70710678 -0.70710678]



Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного 
количества компонент PCA. В качестве метрики различия предлагаю использовать MSE.*

У PCA есть метод transform и inverse_transofrm. Первый - снижает размерность,
второй - восстанавливает оригинальные данные с потерей информации. Надо посчитать насколько 
в среднем точно восстанавливается оригинальная картинка в зависимости от количества компонент в PCA.

В качестве справки можно использовать:

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html - Документация по PCA

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html - Документация по MSE

Картинки цифр можно взять отсюда - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html